name: God Object CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a script
        run: echo Hello from God Object

      - id: foo
        uses: god-object/deploy-action@v0
        with:
          who-to-greet: 'Andy'

      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
